kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  ## Biuld in fips (debug with unittesting)
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

  ## Build in ros melodic
# - name: build-ros-melodic
#   image: amarburg/drone-ci-ros-melodic:latest
#   commands:
#     - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
#   environment:
#     WSTOOL_RECURSIVE: true
#     ROS_PACKAGES_TO_INSTALL: cv-bridge image-transport

  ## Build in ros noetic
- name: build-ros-noetic
  image: amarburg/drone-ci-ros-noetic:latest
  commands:
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
  environment:
    WSTOOL_RECURSIVE: true
    ROS_PACKAGES_TO_INSTALL: cv-bridge image-transport

  ## Trigger downstream builds on Github
# - name: trigger-github-downstream
#   image: plugins/downstream
#   settings:
#     server: https://github.drone.camhd.science
#     fork: true
#     token:
#       from_secret: github_drone_token
#     repositories:
#       - apl-ocean-engineering/serdp_common
#   when:
#     event:
#       exclude:
#         - pull_request

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
    event:
      exclude:
        - pull_request
